name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: "21"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Minecraft Mods Fabric
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 284324
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: 72GXx2MO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            Fabric/build/libs/!(*-@(javadoc|sources)).jar
            Fabric/build/libs/*-@(javadoc|sources).jar
          version-type: beta
          loaders: |
            fabric
            quilt
          game-versions: |
            1.21
            1.21.1
            1.21.2-alpha.24.40.a
          java: 21
          name: ""
          changelog: "https://github.com/InnovativeOnlineIndustries/Emojiful/commits/1.21"
      - name: Publish Minecraft Mods NeoForge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 284324
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: 72GXx2MO
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: |
            NeoForge/build/libs/*-all.jar
            NeoForge/build/libs/!(*-@(all)).jar
          version-type: beta
          loaders: neoforge
          game-versions: |
            1.21
            1.21.1
            1.21.2-alpha.24.40.a
          java: 21
          name: ""
          changelog: "https://github.com/InnovativeOnlineIndustries/Emojiful/commits/1.21"
